name: ssh-agent
description: Start a per-step ssh-agent, load SSH keys defined by paths or environment variables
author: https://github.com/staticfloat
configuration:
  properties:
    # An array of keyfile paths to load
    keyfiles:
      type: array

    # An array of variables that contain (base64-encoded) keyfiles
    keyvars:
      type: array

    # If you want the ssh-agent to store its socket at a particular path, list it here
    socket:
      type: string
  additionalProperties: false
